services:
  react-dashboard:
    image: mbrazalez/dashboard:latest
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BROKER_IP: test.mosquitto.org
      REACT_APP_OPEN_PORT: 8080 

  api-cep:
    image: mbrazalez/api4eventprocessing:latest
    environment:
      SPRING_APPLICATION_NAME: API4EventProcessing
      BROKER_IP: test.mosquitto.org
      OPEN_PORT: 1883
    ports:
      - "8080:8080"

  node-red:
    image: mbrazalez/node-red-custom:latest
    environment:
      - MQTT_BROKER_ADDRESS=test.mosquitto.org
    ports:
      - "1880:1880"
    volumes:
      - node_red_data:/data
      
volumes:
  node_red_data:

  
